apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: node-app
  labels:
    app: node-app
  namespace: application
spec:
  replicas: 2
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 209479307963.dkr.ecr.ap-southeast-2.amazonaws.com/node-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: node-app
        resources:
          limits:
            cpu: "50m"
            memory: "150Mi"
          requests:
            cpu: "50m"
            memory: "150Mi"
